<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        cls_atencion
* GENERATION DATE:  13.04.2019
* CLASS FILE:       /var/www/generator/generated_classes/class.cls_atencion.php
* FOR MYSQL TABLE:  atencion
* FOR MYSQL DB:     sysoft
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

require_once("../conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cls_atencion
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id_atencion;   // KEY ATTR. WITH AUTOINCREMENT

var $id_agenda;   // (normal Attribute)
var $licencia_medica;   // (normal Attribute)
var $receta_medica;   // (normal Attribute)
var $time_atencion;   // (normal Attribute)
var $evolucion_atencion;   // (normal Attribute)
var $tratamiento_atencion;   // (normal Attribute)
var $especialista_atencion;   // (normal Attribute)
var $motivo_atencion;   // (normal Attribute)
var $antecedente_atencion;   // (normal Attribute)
var $ex_fisico_atencion;   // (normal Attribute)
var $oftalmoscopia_atencion;   // (normal Attribute)
var $diagnostico_atencion;   // (normal Attribute)
var $indicacion_atencion;   // (normal Attribute)
var $biomicroscopia_atencion; 
var $arratencion;
var $estado_paciente_atencion;
var $prestacion_atencion;
var $id_paciente;

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function cls_atencion()
{

$this->database = new MySQL();

}


// **********************
// GETTER METHODS
// **********************


function getid_atencion()
{
return $this->id_atencion;
}

function getid_agenda()
{
return $this->id_agenda;
}

function getlicencia_medica()
{
return $this->licencia_medica;
}

function getreceta_medica()
{
return $this->receta_medica;
}

function gettime_atencion()
{
return $this->time_atencion;
}

function getevolucion_atencion()
{
return $this->evolucion_atencion;
}

function gettratamiento_atencion()
{
return $this->tratamiento_atencion;
}

function getespecialista_atencion()
{
return $this->especialista_atencion;
}

function getmotivo_atencion()
{
return $this->motivo_atencion;
}

function getantecedente_atencion()
{
return $this->antecedente_atencion;
}

function getex_fisico_atencion()
{
return $this->ex_fisico_atencion;
}

function getoftalmoscopia_atencion()
{
return $this->oftalmoscopia_atencion;
}

function getdiagnostico_atencion()
{
return $this->diagnostico_atencion;
}

function getindicacion_atencion()
{
return $this->indicacion_atencion;
}
function getbiomicroscopia_atencion()
{
return $this->biomicroscopia_atencion;
}
function getestado_paciente_atencion()
{
return $this->estado_paciente_atencion;
}
function getprestacion_atencion()
{
return $this->prestacion_atencion;
}
   function getid_paciente()
   {
    return $this->id_paciente;
   }
// **********************
// SETTER METHODS
// **********************


function setid_atencion($val)
{
$this->id_atencion =  $val;
}

function setid_agenda($val)
{
$this->id_agenda =  $val;
}

function setlicencia_medica($val)
{
$this->licencia_medica =  $val;
}

function setreceta_medica($val)
{
$this->receta_medica =  $val;
}

function settime_atencion($val)
{
$this->time_atencion =  $val;
}

function setevolucion_atencion($val)
{
$this->evolucion_atencion =  $val;
}

function settratamiento_atencion($val)
{
$this->tratamiento_atencion =  $val;
}

function setespecialista_atencion($val)
{
$this->especialista_atencion =  $val;
}

function setmotivo_atencion($val)
{
$this->motivo_atencion =  $val;
}

function setantecedente_atencion($val)
{
$this->antecedente_atencion =  $val;
}

function setex_fisico_atencion($val)
{
$this->ex_fisico_atencion =  $val;
}

function setoftalmoscopia_atencion($val)
{
$this->oftalmoscopia_atencion =  $val;
}

function setdiagnostico_atencion($val)
{
$this->diagnostico_atencion =  $val;
}

function setindicacion_atencion($val)
{
$this->indicacion_atencion =  $val;
}
function setbiomicroscopia_atencion($val)
{
$this->biomicroscopia_atencion =  $val;
}
function setestado_paciente_atencion($val)
{
$this->estado_paciente_atencion =  $val;
}
function setprestacion_atencion($val)
{
$this->prestacion_atencion =  $val;
}
   function setid_paciente($val)
   {
      $this->id_paciente = $val;
   }
// **********************
// SELECT METHOD / LOAD
// **********************
function msoagendaxpaciente(){
   
    //$id_agenda= $this->getid_agenda();
 //$sql = "SELECT * FROM atencion a WHERE id_agenda = '$id_agenda' order by a.time_atencion asc limit 1 ;"  ;         
 $id_paciente = $this->getid_paciente();
 //$sql = "SELECT * FROM  agenda a  inner join paciente p on p.id_paciente = a.id_paciente inner join atencion"
   //  . " at on at.id_agenda = a.id_agenda WHERE  p.id_paciente = '$id_paciente' order by at.time_atencion asc";
  $sql = "SELECT a.id_agenda,a.estado_agenda,a.prestacion, p.nombre_prestacion, a.fecha_atencion, a.hora_atencion, a.tipo_pago,pg.nombre_pago,"
          . "at.id_atencion, at.licencia_medica, at.time_atencion, at.evolucion_atencion, at.tratamiento_atencion,"
          . "at.estado_paciente_atencion, at.motivo_atencion  "
          . " FROM  agenda a  left join atencion at on at.id_agenda = a.id_agenda "
          . "left join prestacion p on p.id_prestacion = a.prestacion "
          . "left join pago pg on pg.id_pago = a.tipo_pago WHERE  a.id_paciente = '$id_paciente' order by a.fecha_atencion desc";
  $result = $this->database->consulta($sql);
  $i=0;
           while($datos = $this->database->fetch_array($result)){
$this->arratencion[$i]['id_atencion'] = $datos['id_atencion'];    
 
  $this->arratencion[$i]['id_agenda']   		= $datos['id_agenda'];  
   $this->arratencion[$i]['estado_agenda']   		= $datos['estado_agenda'];  

$this->arratencion[$i]['licencia_medica']   	= $datos['licencia_medica'];    
$this->arratencion[$i]['receta_medica']    	= $datos['receta_medica'];    
$this->arratencion[$i]['time_atencion']   	= $datos['time_atencion'];   
$this->arratencion[$i]['evolucion_atencion'] 	= $datos['evolucion_atencion'];    
$this->arratencion[$i]['tratamiento_atencion']  = $datos['tratamiento_atencion'];    
//$this->arratencion[$i]['especialista_atencion'] = $datos['especialista_atencion'];   
$this->arratencion[$i]['estado_paciente_atencion']	= $datos['estado_paciente_atencion'];  
//$this->arratencion[$i]['prestacion_atencion']	         = $datos['prestacion_atencion']; 

$this->arratencion[$i]['motivo_atencion']	= $datos['motivo_atencion'];  
$this->arratencion[$i]['antecedente_atencion']	= $datos['antecedente_atencion']; 
$this->arratencion[$i]['ex_fisico_atencion']	= $datos['ex_fisico_atencion']; 
$this->arratencion[$i]['biomicroscopia_atencion']	= $datos['biomicroscopia_atencion']; 
$this->arratencion[$i]['oftalmoscopia_atencion']	= $datos['oftalmoscopia_atencion']; 
$this->arratencion[$i]['diagnostico_atencion']	= $datos['diagnostico_atencion']; 
$this->arratencion[$i]['indicacion_atencion']	= $datos['indicacion_atencion']; 

$this->arratencion[$i]['nombre_prestacion']	= $datos['nombre_prestacion']; 
$this->arratencion[$i]['prestacion']	= $datos['prestacion']; 
$this->arratencion[$i]['fecha_atencion']	= $datos['fecha_atencion']; 
$this->arratencion[$i]['hora_atencion']	= $datos['hora_atencion']; 
$this->arratencion[$i]['tipo_pago']	= $datos['tipo_pago']; 
$this->arratencion[$i]['nombre_pago']	= $datos['nombre_pago']; 


              $i++;
          }   
}
function msoatencionxpaciente(){
    //$id_agenda= $this->getid_agenda();
 //$sql = "SELECT * FROM atencion a WHERE id_agenda = '$id_agenda' order by a.time_atencion asc limit 1 ;"  ;         
 $id_paciente = $this->getid_paciente();
 $sql = "SELECT * FROM  agenda a  inner join paciente p on p.id_paciente = a.id_paciente inner join atencion"
     . " at on at.id_agenda = a.id_agenda WHERE  p.id_paciente = '$id_paciente' order by a.fecha_agenda desc";
 
  $result = $this->database->consulta($sql);
  $i=0;
           while($datos = $this->database->fetch_array($result)){
$this->arratencion[$i]['id_atencion'] = $datos['id_atencion'];    
$this->arratencion[$i]['id_agenda']   		= $datos['id_agenda']; 
$this->arratencion[$i]['estado_agenda']   		= $datos['estado_agenda'];  

$this->arratencion[$i]['licencia_medica']   	= $datos['licencia_medica'];    
$this->arratencion[$i]['receta_medica']    	= $datos['receta_medica'];    
$this->arratencion[$i]['time_atencion']   	= $datos['time_atencion'];   
$this->arratencion[$i]['evolucion_atencion'] 	= $datos['evolucion_atencion'];    
$this->arratencion[$i]['tratamiento_atencion']  = $datos['tratamiento_atencion'];    
$this->arratencion[$i]['especialista_atencion'] = $datos['especialista_atencion'];   
$this->arratencion[$i]['estado_paciente_atencion']	= $datos['estado_paciente_atencion'];  
$this->arratencion[$i]['prestacion_atencion']	         = $datos['prestacion_atencion']; 

$this->arratencion[$i]['motivo_atencion']	= $datos['motivo_atencion'];  
$this->arratencion[$i]['antecedente_atencion']	= $datos['antecedente_atencion']; 
$this->arratencion[$i]['ex_fisico_atencion']	= $datos['ex_fisico_atencion']; 
$this->arratencion[$i]['biomicroscopia_atencion']	= $datos['biomicroscopia_atencion']; 
$this->arratencion[$i]['oftalmoscopia_atencion']	= $datos['oftalmoscopia_atencion']; 
$this->arratencion[$i]['diagnostico_atencion']	= $datos['diagnostico_atencion']; 
$this->arratencion[$i]['indicacion_atencion']	= $datos['indicacion_atencion']; 

$this->arratencion[$i]['prestacion']	= $datos['prestacion']; 
$this->arratencion[$i]['fecha_atencion']	= $datos['fecha_atencion']; 
$this->arratencion[$i]['hora_atencion']	= $datos['hora_atencion']; 
$this->arratencion[$i]['tipo_pago']	= $datos['tipo_pago']; 

              $i++;
          }   
}

function msoatencionagendada(){
    $id_agenda= $this->getid_agenda();
    
 $sql = "SELECT * FROM atencion at inner join agenda a on a.id_agenda = at.id_agenda "
         . "WHERE at.id_agenda = '$id_agenda' order by at.time_atencion asc limit 1 ;"  ;         
  $result = $this->database->consulta($sql);
  $i=0;
           while($datos = $this->database->fetch_array($result)){
$this->arratencion[$i]['estado_agenda']   		= $datos['estado_agenda'];                
               
$this->arratencion[$i]['id_atencion'] = $datos['id_atencion'];    
$this->arratencion[$i]['id_agenda']   		= $datos['id_agenda'];   
$this->arratencion[$i]['licencia_medica']   	= $datos['licencia_medica'];    
$this->arratencion[$i]['receta_medica']    	= $datos['receta_medica'];    
$this->arratencion[$i]['time_atencion']   	= $datos['time_atencion'];   
$this->arratencion[$i]['evolucion_atencion'] 	= $datos['evolucion_atencion'];    
$this->arratencion[$i]['tratamiento_atencion']  = $datos['tratamiento_atencion'];    
$this->arratencion[$i]['especialista_atencion'] = $datos['especialista_atencion'];   
$this->arratencion[$i]['estado_paciente_atencion']	= $datos['estado_paciente_atencion'];  
$this->arratencion[$i]['prestacion_atencion']	         = $datos['prestacion_atencion']; 

$this->arratencion[$i]['motivo_atencion']	= $datos['motivo_atencion'];  
$this->arratencion[$i]['antecedente_atencion']	= $datos['antecedente_atencion']; 
$this->arratencion[$i]['ex_fisico_atencion']	= $datos['ex_fisico_atencion']; 
$this->arratencion[$i]['biomicroscopia_atencion']	= $datos['biomicroscopia_atencion']; 
$this->arratencion[$i]['oftalmoscopia_atencion']	= $datos['oftalmoscopia_atencion']; 
$this->arratencion[$i]['diagnostico_atencion']	= $datos['diagnostico_atencion']; 
$this->arratencion[$i]['indicacion_atencion']	= $datos['indicacion_atencion']; 
              $i++;
          }   
}

function select($id)
{

$sql =  "SELECT * FROM atencion WHERE id_atencion = $id;";
$result =  $this->database->consulta($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->id_atencion = $row->id_atencion;

$this->id_agenda = $row->id_agenda;

$this->licencia_medica = $row->licencia_medica;

$this->receta_medica = $row->receta_medica;

$this->time_atencion = $row->time_atencion;

$this->evolucion_atencion = $row->evolucion_atencion;

$this->tratamiento_atencion = $row->tratamiento_atencion;

$this->especialista_atencion = $row->especialista_atencion;

$this->motivo_atencion = $row->motivo_atencion;

$this->antecedente_atencion = $row->antecedente_atencion;

$this->ex_fisico_atencion = $row->ex_fisico_atencion;

$this->oftalmoscopia_atencion = $row->oftalmoscopia_atencion;

$this->diagnostico_atencion = $row->diagnostico_atencion;

$this->indicacion_atencion = $row->indicacion_atencion;
$this->biomicroscopia_atencion = $row->biomicroscopia_atencion;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM atencion WHERE id_atencion = $id;";
$result = $this->database->consulta($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id_atencion = ""; // clear key for autoincrement

$sql = "INSERT INTO atencion "
 . "( id_agenda,licencia_medica,receta_medica,evolucion_atencion,tratamiento_atencion,"
 . "especialista_atencion,motivo_atencion,antecedente_atencion,ex_fisico_atencion,oftalmoscopia_atencion,"
 . "biomicroscopia_atencion,diagnostico_atencion,indicacion_atencion,estado_paciente_atencion,prestacion_atencion ) VALUES "
        . "( '$this->id_agenda','$this->licencia_medica','$this->receta_medica',"
        . "'$this->evolucion_atencion','$this->tratamiento_atencion','$this->especialista_atencion',"
        . "'$this->motivo_atencion','$this->antecedente_atencion','$this->ex_fisico_atencion',"
        . "'$this->oftalmoscopia_atencion','$this->biomicroscopia_atencion','$this->diagnostico_atencion',"
        . "'$this->indicacion_atencion','$this->estado_paciente_atencion','$this->prestacion_atencion' )";
$result = $this->database->consulta($sql);
$this->id_atencion = mysql_insert_id();

}

// **********************
// UPDATE
// **********************

function update()
{

//$id_atencion= $this->id_atencion;
$id_agenda = $this->id_agenda;
$sql = " UPDATE atencion SET  licencia_medica = '$this->licencia_medica',"
        . "receta_medica = '$this->receta_medica',time_atencion = '$this->time_atencion',"
        . "evolucion_atencion = '$this->evolucion_atencion',tratamiento_atencion = '$this->tratamiento_atencion',"
        . "especialista_atencion = '$this->especialista_atencion',motivo_atencion = '$this->motivo_atencion',"
        . "antecedente_atencion = '$this->antecedente_atencion',ex_fisico_atencion = '$this->ex_fisico_atencion',"
        . "oftalmoscopia_atencion = '$this->oftalmoscopia_atencion',biomicroscopia_atencion = '$this->biomicroscopia_atencion',"
        . "diagnostico_atencion = '$this->diagnostico_atencion',"
        . "estado_paciente_atencion = '$this->estado_paciente_atencion',"
        . "prestacion_atencion = '$this->prestacion_atencion',"
        . "indicacion_atencion = '$this->indicacion_atencion' WHERE id_agenda = '$id_agenda' order by time_atencion asc limit 1 ; ";

$result = $this->database->consulta($sql);



}


}