<?php
require_once('../clases/cls_lente.php');
/*
*
* -------------------------------------------------------
* CLASSNAME:        cls_lente
* GENERATION DATE:  13.04.2019
* CLASS FILE:       /var/www/generator/generated_classes/class.cls_lente.php
* FOR MYSQL TABLE:  lente
* FOR MYSQL DB:     sysoft
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

require_once("../conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cls_lente
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $cod_lente;   // KEY ATTR. WITH AUTOINCREMENT

var $tipo_lente;   // (normal Attribute)
var $nombre_lente;   // (normal Attribute)
var $arrlente;

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function cls_lente()
{

$this->database = new MySQL();

}


// **********************
// GETTER METHODS
// **********************


function getcod_lente()
{
return $this->cod_lente;
}

function gettipo_lente()
{
return $this->tipo_lente;
}

function getnombre_lente()
{
return $this->nombre_lente;
}

// **********************
// SETTER METHODS
// **********************


function setcod_lente($val)
{
$this->cod_lente =  $val;
}

function settipo_lente($val)
{
$this->tipo_lente =  $val;
}

function setnombre_lente($val)
{
$this->nombre_lente =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************
function selectdatatipo()
{
$tipo_lente = $this->gettipo_lente();
$sql =  "SELECT * FROM lente WHERE tipo_lente = '$tipo_lente'";
$result = $this->database->consulta($sql);
 $i=0;
    while($datos = $this->database->fetch_array($result)){
      $this->arrlente[$i]['cod_lente'] = $datos['cod_lente'];    
      $this->arrlente[$i]['tipo_lente']  = $datos['tipo_lente'];   
      $this->arrlente[$i]['nombre_lente']  = $datos['nombre_lente'];  
         $i++;
    } 
}
function selectdata()
{

$sql =  "SELECT * FROM lente WHERE 1";
$result = $this->database->consulta($sql);
 $i=0;
    while($datos = $this->database->fetch_array($result)){
      $this->arrlente[$i]['cod_lente'] = $datos['cod_lente'];    
      $this->arrlente[$i]['tipo_lente']  = $datos['tipo_lente'];   
      $this->arrlente[$i]['nombre_lente']  = $datos['nombre_lente'];  
         $i++;
    } 
}
function select($id)
{

$sql =  "SELECT * FROM lente WHERE cod_lente = $id;";
$result =  $this->database->consulta($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->cod_lente = $row->cod_lente;

$this->tipo_lente = $row->tipo_lente;

$this->nombre_lente = $row->nombre_lente;

}

// **********************
// DELETE
// **********************

function delete()
{
$tipo_lente = $this->gettipo_lente();
$sql = "DELETE * FROM lente WHERE tipo_lente = '$tipo_lente'";
$result = $this->database->consulta($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->cod_lente = ""; // clear key for autoincrement

$sql = "INSERT INTO lente ( tipo_lente,nombre_lente ) VALUES ( '$this->tipo_lente','$this->nombre_lente' )";
$result = $this->database->consulta($sql);
$this->cod_lente = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE lente SET  tipo_lente = '$this->tipo_lente',nombre_lente = '$this->nombre_lente' WHERE cod_lente = $id ";

$result = $this->database->consulta($sql);



}
}