
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        cls_acceso
* GENERATION DATE:  05.10.2017
* CLASS FILE:       /var/www/generator/generated_classes/class.cls_acceso.php
* FOR MYSQL TABLE:  acceso
* FOR MYSQL DB:     pacientes10
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

require_once("../conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cls_acceso
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id_acceso;   // KEY ATTR. WITH AUTOINCREMENT

var $rut_personal;   // (normal Attribute)
var $pwd_actual;   // (normal Attribute)
var $pwd_last;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function cls_acceso()
{

$this->database = new MySQL();

}


// **********************
// GETTER METHODS
// **********************


function getid_acceso()
{
return $this->id_acceso;
}

function getrut_personal()
{
return $this->rut_personal;
}

function getpwd_actual()
{
return $this->pwd_actual;
}

function getpwd_last()
{
return $this->pwd_last;
}

// **********************
// SETTER METHODS
// **********************


function setid_acceso($val)
{
$this->id_acceso =  $val;
}

function setrut_personal($val)
{
$this->rut_personal =  $val;
}

function setpwd_actual($val)
{
$this->pwd_actual =  $val;
}

function setpwd_last($val)
{
$this->pwd_last =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************
function obtacceso($dv)
{
//$rut = $this->getrut_personal();
$this->id_acceso= '';
$rut = $this->getrut_personal().'%-'.trim($dv);
$pass = $this->getpwd_actual();


//$sql =  "SELECT * FROM acceso WHERE rut_personal LIKE '$rut' and pwd_actual = '$pass';";
$sql =  "SELECT * FROM acceso WHERE rut_personal LIKE '$rut' ;";
$result =  $this->database->consulta($sql);
//$result = $this->database->result;
$row = $this->database->fetch_array($result);
//$row = mysql_fetch_object($result);


$this->id_acceso = $row['id_acceso'];

$this->rut_personal = $row['rut_personal'];

$this->pwd_actual = $row['pwd_actual'];

$this->pwd_last = $row['pwd_last'];

}



function select($id)
{

$sql =  "SELECT * FROM acceso WHERE id_acceso = $id;";
$result =  $this->database->consulta($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->id_acceso = $row->id_acceso;

$this->rut_personal = $row->rut_personal;

$this->pwd_actual = $row->pwd_actual;

$this->pwd_last = $row->pwd_last;

}

// **********************
// DELETE
// **********************

function delete($dv)
{
$search = $this->getrut_personal().'%-'.trim($dv);
$sql = "DELETE FROM acceso WHERE rut_personal LIKE '$search';";
$result = $this->database->consulta($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id_acceso = ""; // clear key for autoincrement

$sql = "INSERT INTO acceso ( rut_personal,pwd_actual,pwd_last ) VALUES "
. "( '$this->rut_personal','$this->pwd_actual','$this->pwd_last' )";
$result = $this->database->consulta($sql);
$this->id_acceso = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE acceso SET  rut_personal = '$this->rut_personal',pwd_actual = '$this->pwd_actual',pwd_last = '$this->pwd_last' WHERE id_acceso = $id ";

$result = $this->database->consulta($sql);



}
function updatepass()
{
$rut_personal = $this->getrut_personal();
$pwd_actual = $this->getpwd_actual();
$pwd_last= $this->getpwd_last();

$sql = " UPDATE acceso SET   pwd_actual = '$pwd_actual',"
        . "pwd_last = '$pwd_last' WHERE rut_personal = '$rut_personal' ";

$result = $this->database->consulta($sql);



}

} // class : end

?>
