<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        cls_prestacion
* GENERATION DATE:  25.04.2019
* CLASS FILE:       /var/www/generator/generated_classes/class.cls_prestacion.php
* FOR MYSQL TABLE:  prestacion
* FOR MYSQL DB:     pacientes12
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

require_once("../conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cls_prestacion
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id_prestacion;   // KEY ATTR. WITH AUTOINCREMENT

var $id_especialidad;   // (normal Attribute)
var $nombre_prestacion;   // (normal Attribute)
var $detalle_prestacion;   // (normal Attribute)
var $precio_prestacion;   // (normal Attribute)
var $arrprestacion;

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function cls_prestacion()
{

   $this->database = new MySQL();

}


// **********************
// GETTER METHODS
// **********************


function getid_prestacion()
{
return $this->id_prestacion;
}

function getid_especialidad()
{
return $this->id_especialidad;
}

function getnombre_prestacion()
{
return $this->nombre_prestacion;
}

function getdetalle_prestacion()
{
return $this->detalle_prestacion;
}

function getprecio_prestacion()
{
return $this->precio_prestacion;
}

// **********************
// SETTER METHODS
// **********************


function setid_prestacion($val)
{
$this->id_prestacion =  $val;
}

function setid_especialidad($val)
{
$this->id_especialidad =  $val;
}

function setnombre_prestacion($val)
{
$this->nombre_prestacion =  $val;
}

function setdetalle_prestacion($val)
{
$this->detalle_prestacion =  $val;
}

function setprecio_prestacion($val)
{
$this->precio_prestacion =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function estadistica(){
   

  $sql = "SELECT  p.id_prestacion,p.nombre_prestacion, pg.id_pago,count(a.tipo_pago) as t_pagos "
  . "FROM prestacion p left join agenda  a  on p.id_prestacion = a.prestacion "
  . "left join pago pg on pg.id_pago = a.tipo_pago  "
  . "where 1  group by p.id_prestacion,  pg.id_pago order by p.id_prestacion, pg.id_pago asc";
  $result = $this->database->consulta($sql);
  $i=0;
  while($datos = $this->database->fetch_array($result)){
      
   $this->arrprestacion[$i]['id_prestacion'] = $datos['id_prestacion'];          
   $this->arrprestacion[$i]['nombre_prestacion'] = $datos['nombre_prestacion']; 
   $this->arrprestacion[$i]['id_pago'] = $datos['id_pago']; 
   $this->arrprestacion[$i]['t_pagos'] = $datos['t_pagos']; 
 //  $this->arrprestacion[$i]['nombre_especialidad'] = $datos['nombre_especialidad']; 
  
   $i++;
  }
 }

function lstprestacion2(){
   

  $sql = "SELECT * FROM prestacion WHERE 1 order by id_prestacion asc";
  $result = $this->database->consulta($sql);
  $i=0;
  while($datos = $this->database->fetch_array($result)){
      
   $this->arrprestacion[$i]['id_prestacion'] = $datos['id_prestacion'];          
   $this->arrprestacion[$i]['nombre_prestacion'] = $datos['nombre_prestacion']; 
   $this->arrprestacion[$i]['color_prestacion'] = $datos['color_prestacion']; 
      $this->arrprestacion[$i]['estado_prestacion'] = $datos['estado_prestacion']; 
 // $this->arrprestacion[$i]['id_especialidad'] = $datos['id_especialidad']; 
 //  $this->arrprestacion[$i]['nombre_especialidad'] = $datos['nombre_especialidad']; 
  
   $i++;
  }
 }

function lstprestacion(){
  $id_especialidad = $this->getid_especialidad();  
 // $sql = "SELECT * FROM prestacion p inner join especialidad e on p.id_especialidad = e.id_especialidad"
 // . "  WHERE 1 order by p.id_especialidad, p.nombre_prestacion asc" ; 
  $sql = "SELECT * FROM atiende a inner join prestacion p on p.id_prestacion = a.id_prestacion"
  . " inner join especialidad e on e.id_especialidad = a.id_especialidad  "
  . " WHERE a.id_especialidad = '$id_especialidad' order by e.id_especialidad,  p.nombre_prestacion asc";
  $result = $this->database->consulta($sql);
  $i=0;
  while($datos = $this->database->fetch_array($result)){
      
   $this->arrprestacion[$i]['id_prestacion'] = $datos['id_prestacion'];          
   $this->arrprestacion[$i]['nombre_prestacion'] = $datos['nombre_prestacion']; 
   $this->arrprestacion[$i]['id_especialidad'] = $datos['id_especialidad']; 
   $this->arrprestacion[$i]['nombre_especialidad'] = $datos['nombre_especialidad']; 
  
   $i++;
  }
 }

function select($id)
{

$sql =  "SELECT * FROM prestacion WHERE id_prestacion = $id;";
$result =  $this->database->consulta($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->id_prestacion = $row->id_prestacion;

$this->id_especialidad = $row->id_especialidad;

$this->nombre_prestacion = $row->nombre_prestacion;

$this->detalle_prestacion = $row->detalle_prestacion;

$this->precio_prestacion = $row->precio_prestacion;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM prestacion WHERE id_prestacion = $id;";
$result = $this->database->consulta($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id_prestacion = ""; // clear key for autoincrement

$sql = "INSERT INTO prestacion ( id_especialidad,nombre_prestacion,detalle_prestacion,precio_prestacion ) VALUES ( '$this->id_especialidad','$this->nombre_prestacion','$this->detalle_prestacion','$this->precio_prestacion' )";
$result = $this->database->consulta($sql);
$this->id_prestacion = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE prestacion SET  id_especialidad = '$this->id_especialidad',nombre_prestacion = '$this->nombre_prestacion',detalle_prestacion = '$this->detalle_prestacion',precio_prestacion = '$this->precio_prestacion' WHERE id_prestacion = $id ";

$result = $this->database->consulta($sql);



}


} // class : end

?>