<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        cls_pago
* GENERATION DATE:  01.06.2019
* CLASS FILE:       /var/www/generator/generated_classes/class.cls_pago.php
* FOR MYSQL TABLE:  pago
* FOR MYSQL DB:     sysoft
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

require_once("../conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cls_pago
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id_pago;   // KEY ATTR. WITH AUTOINCREMENT

var $nombre_pago;   // (normal Attribute)
var $detalle_pago;   // (normal Attribute)
var $estado_pago;   // (normal Attribute)
var $arrpago;

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function cls_pago()
{

   $this->database = new MySQL();

}


// **********************
// GETTER METHODS
// **********************


function getid_pago()
{
return $this->id_pago;
}

function getnombre_pago()
{
return $this->nombre_pago;
}

function getdetalle_pago()
{
return $this->detalle_pago;
}

function getestado_pago()
{
return $this->estado_pago;
}

// **********************
// SETTER METHODS
// **********************


function setid_pago($val)
{
$this->id_pago =  $val;
}

function setnombre_pago($val)
{
$this->nombre_pago =  $val;
}

function setdetalle_pago($val)
{
$this->detalle_pago =  $val;
}

function setestado_pago($val)
{
$this->estado_pago =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************
function estadistica_resumen(){
  $sql = "SELECT  count(a.tipo_pago) as t_pagos, pg.cat_pago  FROM pago  pg left join agenda  a  "
          . "on   pg.id_pago = a.tipo_pago  where 1  group by   pg.cat_pago order by  pg.cat_pago asc";
  $result = $this->database->consulta($sql);
  $i=0;
  while($datos = $this->database->fetch_array($result)){
      
   $this->arrpago[$i]['cat_pago'] = $datos['cat_pago']; 
 //  $this->arrpago[$i]['id_pago'] = $datos['id_pago']; 
   $this->arrpago[$i]['t_pagos'] = $datos['t_pagos']; 
 //  $this->arrprestacion[$i]['nombre_especialidad'] = $datos['nombre_especialidad']; 
  
   $i++;
  }
 }
function estadistica(){
  $sql = "SELECT  count(a.tipo_pago) as t_pagos, pg.nombre_pago, pg.id_pago "
  . "FROM pago  pg left join agenda  a  on pg.id_pago = a.tipo_pago  "
  . "where 1  group by   pg.id_pago order by  pg.id_pago asc";
  $result = $this->database->consulta($sql);
  $i=0;
  while($datos = $this->database->fetch_array($result)){
      
   $this->arrpago[$i]['nombre_pago'] = $datos['nombre_pago']; 
   $this->arrpago[$i]['id_pago'] = $datos['id_pago']; 
   $this->arrpago[$i]['t_pagos'] = $datos['t_pagos']; 
 //  $this->arrprestacion[$i]['nombre_especialidad'] = $datos['nombre_especialidad']; 
  
   $i++;
  }
 }
function lstpago(){
   

  $sql = "SELECT * FROM pago WHERE  1 order by id_pago asc";
  $result = $this->database->consulta($sql);
  $i=0;
  while($datos = $this->database->fetch_array($result)){
      
   $this->arrpago[$i]['id_pago'] = $datos['id_pago'];          
   $this->arrpago[$i]['nombre_pago'] = $datos['nombre_pago']; 
    $this->arrpago[$i]['color_pago'] = $datos['color_pago']; 
 //  $this->arrprestacion[$i]['id_especialidad'] = $datos['id_especialidad']; 
 //  $this->arrprestacion[$i]['nombre_especialidad'] = $datos['nombre_especialidad']; 
  
   $i++;
  }
 }

function select($id)
{

$sql =  "SELECT * FROM pago WHERE id_pago = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->id_pago = $row->id_pago;

$this->nombre_pago = $row->nombre_pago;

$this->detalle_pago = $row->detalle_pago;

$this->estado_pago = $row->estado_pago;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM pago WHERE id_pago = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id_pago = ""; // clear key for autoincrement

$sql = "INSERT INTO pago ( nombre_pago,detalle_pago,estado_pago ) VALUES ( '$this->nombre_pago','$this->detalle_pago','$this->estado_pago' )";
$result = $this->database->query($sql);
$this->id_pago = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE pago SET  nombre_pago = '$this->nombre_pago',detalle_pago = '$this->detalle_pago',estado_pago = '$this->estado_pago' WHERE id_pago = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>