<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        cls_servicio_elemento
* GENERATION DATE:  12.02.2020
* CLASS FILE:       C:\xampp\htdocs\generator/generated_classes/class.cls_servicio_elemento.php
* FOR MYSQL TABLE:  servicio_elemento
* FOR MYSQL DB:     erp
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

require_once("../conexion/conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cls_servicio_elemento
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $selem_id;   // KEY ATTR. WITH AUTOINCREMENT

var $selem_maquina;   // (normal Attribute)
var $arrelemento;

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function cls_servicio_elemento()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getselem_id()
{
return $this->selem_id;
}

function getselem_maquina()
{
return $this->selem_maquina;
}

// **********************
// SETTER METHODS
// **********************


function setselem_id($val)
{
$this->selem_id =  $val;
}

function setselem_maquina($val)
{
$this->selem_maquina =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function selectdata()
{

$sql =  "SELECT * FROM servicio_elemento WHERE 1 order by selem_id asc;";
$result =  $this->database->query($sql);
$result = $this->database->query($sql);
 $i=0;
    while($datos = $this->database->fetch_array($result)){
        $this->arrelemento[$i]['selem_id'] = $datos['selem_id']; 
        $this->arrelemento[$i]['selem_maquina'] = $datos['selem_maquina']; 
     $i++;
    } 
 

}

function select($id)
{

$sql =  "SELECT * FROM servicio_elemento WHERE selem_id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->selem_id = $row->selem_id;

$this->selem_maquina = $row->selem_maquina;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM servicio_elemento WHERE selem_id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->selem_id = ""; // clear key for autoincrement

$sql = "INSERT INTO servicio_elemento ( selem_maquina ) VALUES ( '$this->selem_maquina' )";
$result = $this->database->query($sql);
$this->selem_id = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE servicio_elemento SET  selem_maquina = '$this->selem_maquina' WHERE selem_id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>