<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        cls_proc_marca
* GENERATION DATE:  14.01.2020
* CLASS FILE:       C:\xampp\htdocs\generator/generated_classes/class.cls_proc_marca.php
* FOR MYSQL TABLE:  proc_marca
* FOR MYSQL DB:     erp
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

require_once("../conexion/conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cls_proc_marca
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $marca_id;   // KEY ATTR. WITH AUTOINCREMENT

var $pro_marca_id;   // (normal Attribute)
var $marca_nombre;   // (normal Attribute)
var $marca_color;
var $marca_tipo;
var $marca_etiqueta;

var $arrmarca;
var $arrsbmarca;
var $arrsbsbmarca;
var $total_marcaegoria;
var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function cls_proc_marca()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getmarca_id()
{
return $this->marca_id;
}

function getpro_marca_id()
{
return $this->pro_marca_id;
}

function getmarca_nombre()
{
return $this->marca_nombre;
}
function getmarca_color()
{
return $this->marca_color;
}
function getmarca_tipo()
{
return $this->marca_tipo;
}
function getmarca_etiqueta()
{
return $this->marca_etiqueta;
}
function gettotal_marcaegoria()
{
return $this->total_marcaegoria;
}
// **********************
// SETTER METHODS
// **********************


function setmarca_id($val)
{
$this->marca_id =  $val;
}

function setpro_marca_id($val)
{
$this->pro_marca_id =  $val;
}

function setmarca_nombre($val)
{
$this->marca_nombre =  $val;
}
function setmarca_color($val)
{
$this->marca_color =  $val;
}
function setmarca_tipo($val)
{
$this->marca_tipo =  $val;
}
function setmarca_etiqueta($val)
{
$this->marca_etiqueta =  $val;
}
function settotal_marcaegoria($val)
{
$this->total_marcaegoria =  $val;
}
// **********************
// SELECT METHOD / LOAD
// **********************
function buscadatanombre()
{
$marca_nombre = $this->getmarca_nombre();
//$pro_marca_id = 3;

$sql =  "SELECT * FROM `proc_marca` WHERE marca_nombre = '$marca_nombre' ";
$result =  $this->database->query($sql);
$i=0;
    while($datos = $this->database->fetch_array($result)){
        
        $this->arrmarca[$i]['marca_id'] = $datos['marca_id']; 
     //   $this->arrmarca[$i]['pro_marca_id'] = $datos['parent']; 
        $this->arrmarca[$i]['marca_nombre'] = $datos['marca_nombre']; 
        $this->arrmarca[$i]['marca_etiqueta'] = $datos['marca_etiqueta']; 
    //    $this->arrmarca[$i]['marca_color'] = $datos['marca_color']; 
     //   $this->arrmarca[$i]['marca_etiqueta'] = $datos['marca_etiqueta']; 
         
     $i++;
    } 
}
function selectdata()
{
$marca_id = $this->getmarca_id();
//$pro_marca_id = 3;

$sql =  "SELECT * FROM `proc_marca` WHERE 1 ";
$result =  $this->database->query($sql);
$i=0;
    while($datos = $this->database->fetch_array($result)){
        
        $this->arrmarca[$i]['marca_id'] = $datos['marca_id']; 
     
        $this->arrmarca[$i]['marca_nombre'] = $datos['marca_nombre']; 
       
         
     $i++;
    } 
}
function selectarbol()
{
$marca_id = $this->getmarca_id();
//$pro_marca_id = 3;

$sql =  "select t.marca_id as id, @pv:=t.pro_marca_id as parent , t.marca_nombre, t.marca_etiqueta "
        . "from (select * from  proc_marca order by marca_id desc) t join "
        . "(select @pv:='$marca_id')tmp where t.marca_id=@pv; ";
$result =  $this->database->query($sql);
$i=0;
    while($datos = $this->database->fetch_array($result)){
        
        $this->arrmarca[$i]['marca_id'] = $datos['id']; 
     //   $this->arrmarca[$i]['pro_marca_id'] = $datos['parent']; 
        $this->arrmarca[$i]['marca_nombre'] = $datos['marca_nombre']; 
        $this->arrmarca[$i]['marca_etiqueta'] = $datos['marca_etiqueta']; 
    //    $this->arrmarca[$i]['marca_color'] = $datos['marca_color']; 
     //   $this->arrmarca[$i]['marca_etiqueta'] = $datos['marca_etiqueta']; 
         
     $i++;
    } 
}
function totalxmarca()
{
$pro_marca_id = $this->getpro_marca_id();
$marca_tipo = $this->getmarca_tipo();
if(!is_null($pro_marca_id))
    $sql =  "SELECT count(*) as total_marcaegoria FROM proc_marca WHERE  pro_marca_id = '$pro_marca_id' and marca_tipo = '$marca_tipo'";
else 
     $sql =  "SELECT count(*) as total_marcaegoria FROM proc_marca WHERE  pro_marca_id is null  and marca_tipo = '$marca_tipo'";
   
$result = $this->database->query($sql);
 $i=0;
    while($datos = $this->database->fetch_array($result)){
       
        $this->total_marcaegoria = $datos['total_marcaegoria'];  
         $i++;
    } 
}
function selectsubmarca()
{
$pro_marca_id = $this->getpro_marca_id();
//$pro_marca_id = 3;
$sql =  "select t.marca_id, t.pro_marca_id , t.marca_nombre, t.marca_etiqueta from (select * from  proc_marca"
        . " order by marca_nombre asc) t join (select @pv:='$pro_marca_id')tmp where  "
        . " find_in_set(pro_marca_id, @pv) and     length(@pv := conmarca(@pv, ',', marca_id ))";
$result =  $this->database->query($sql);
$i=0;
    while($datos = $this->database->fetch_array($result)){
        
        $this->arrmarca[$i]['marca_id'] = $datos['marca_id']; 
   //     $this->arrmarca[$i]['pro_marca_id'] = $datos['pro_marca_id']; 
        $this->arrmarca[$i]['marca_nombre'] = $datos['marca_nombre']; 
        $this->arrmarca[$i]['marca_color'] = $datos['marca_color']; 
        $this->arrmarca[$i]['marca_etiqueta'] = $datos['marca_etiqueta']; 
         
     $i++;
    } 
}
function getmarcageneralxnombre()
{
$marca_nombre = $this->getmarca_nombre();
$marca_tipo = $this->getmarca_tipo();
$sql =  "SELECT * FROM `proc_marca` WHERE `pro_marca_id` is null and marca_tipo = '$marca_tipo' and marca_nombre LIKE '$marca_nombre' "
        . " order by marca_nombre asc  ;";
$result =  $this->database->query($sql);
$i=0;
    while($datos = $this->database->fetch_array($result)){
        
        $this->arrmarca[$i]['marca_id'] = $datos['marca_id']; 
 //       $this->arrmarca[$i]['pro_marca_id'] = $datos['pro_marca_id']; 
        $this->arrmarca[$i]['marca_nombre'] = $datos['marca_nombre']; 
        $this->arrmarca[$i]['marca_color'] = $datos['marca_color']; 
        $this->arrmarca[$i]['marca_etiqueta'] = $datos['marca_etiqueta']; 
     $i++;
    } 
}
function selectgeneral()
{
$marca_tipo = $this->getmarca_tipo();
$sql =  "SELECT * FROM `proc_marca` WHERE `pro_marca_id` is null and marca_tipo = '$marca_tipo' order by marca_nombre asc ;";
$result =  $this->database->query($sql);
$i=0;
    while($datos = $this->database->fetch_array($result)){
        
        $this->arrmarca[$i]['marca_id'] = $datos['marca_id']; 
//        $this->arrmarca[$i]['pro_marca_id'] = $datos['pro_marca_id']; 
        $this->arrmarca[$i]['marca_nombre'] = $datos['marca_nombre']; 
   //     $this->arrmarca[$i]['marca_color'] = $datos['marca_color']; 
    //    $this->arrmarca[$i]['marca_etiqueta'] = $datos['marca_etiqueta']; 
     $i++;
    } 
}

function select($id)
{

$sql =  "SELECT * FROM proc_marca WHERE marca_id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->marca_id = $row->marca_id;

$this->pro_marca_id = $row->pro_marca_id;

$this->marca_nombre = $row->marca_nombre;

}

// **********************
// DELETE
// **********************

function delete()
{
 $id = $this->getmarca_id();
$sql = "DELETE FROM proc_marca WHERE marca_id =  $id ";
$result = $this->database->query($sql);

}
 
// **********************
// INSERT
// **********************

function insert()
{
$this->marca_id = ""; // clear key for autoincrement

     $sql = "INSERT INTO proc_marca (  marca_nombre)"
        . " VALUES (  '$this->marca_nombre' )";
$result = $this->database->query($sql);
$this->marca_id = mysql_insert_id();

}

// **********************
// UPDATE
// **********************
function editar()
{

$id = $this->getmarca_id();

$sql = " UPDATE proc_marca SET  marca_nombre = '$this->marca_nombre' WHERE marca_id = $id ";

$result = $this->database->query($sql);



}
function update()
{



$sql = " UPDATE proc_marca SET  pro_marca_id = '$this->pro_marca_id',marca_nombre = '$this->marca_nombre' WHERE marca_id = $id ";

$result = $this->database->query($sql);



}


} 

?>