<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        cls_solicitud
* GENERATION DATE:  11.04.2021
* CLASS FILE:       C:\xampp\htdocs\generator/generated_classes/class.cls_solicitud.php
* FOR MYSQL TABLE:  ing_solicitud
* FOR MYSQL DB:     erp
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

require_once("../conexion/conexion.php");
// **********************
// CLASS DECLARATION
// **********************

class cls_solicitud
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $solc_id;   // KEY ATTR. WITH AUTOINCREMENT

var $solc_fecha;   // (normal Attribute)
var $solc_destino;   // (normal Attribute)
var $solc_observacion;   // (normal Attribute)
var $solc_usuario;   // (normal Attribute)
var $solc_estado;   // (normal Attribute)
var $solc_tipo;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function cls_solicitud()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getsolc_id()
{
return $this->solc_id;
}

function getsolc_fecha()
{
return $this->solc_fecha;
}

function getsolc_destino()
{
return $this->solc_destino;
}

function getsolc_observacion()
{
return $this->solc_observacion;
}

function getsolc_usuario()
{
return $this->solc_usuario;
}

function getsolc_estado()
{
return $this->solc_estado;
}

function getsolc_tipo()
{
return $this->solc_tipo;
}

// **********************
// SETTER METHODS
// **********************


function setsolc_id($val)
{
$this->solc_id =  $val;
}

function setsolc_fecha($val)
{
$this->solc_fecha =  $val;
}

function setsolc_destino($val)
{
$this->solc_destino =  $val;
}

function setsolc_observacion($val)
{
$this->solc_observacion =  $val;
}

function setsolc_usuario($val)
{
$this->solc_usuario =  $val;
}

function setsolc_estado($val)
{
$this->solc_estado =  $val;
}

function setsolc_tipo($val)
{
$this->solc_tipo =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************
function buscadatanombre()
{
$marca_nombre = $this->getmarca_nombre();
//$pro_marca_id = 3;

$sql =  "SELECT * FROM `proc_marca` WHERE marca_nombre = '$marca_nombre' ";
$result =  $this->database->query($sql);
$i=0;
    while($datos = $this->database->fetch_array($result)){
        
        $this->arrmarca[$i]['marca_id'] = $datos['marca_id']; 
    
        $this->arrmarca[$i]['marca_nombre'] = $datos['marca_nombre']; 
        $this->arrmarca[$i]['marca_etiqueta'] = $datos['marca_etiqueta']; 
    
         
     $i++;
    } 
}
function select($id)
{

$sql =  "SELECT * FROM ing_solicitud WHERE solc_id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->solc_id = $row->solc_id;

$this->solc_fecha = $row->solc_fecha;

$this->solc_destino = $row->solc_destino;

$this->solc_observacion = $row->solc_observacion;

$this->solc_usuario = $row->solc_usuario;

$this->solc_estado = $row->solc_estado;

$this->solc_tipo = $row->solc_tipo;

}

// **********************
// DELETE
// **********************

function delete()
{
 $solc_id= $this->getsolc_id();   
$sql = "DELETE FROM ing_solicitud WHERE solc_id = $solc_id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->solc_id = ""; // clear key for autoincrement
 
$sql = "INSERT INTO ing_solicitud "
        . "( solc_fecha,solc_destino,solc_observacion,solc_usuario,solc_tipo ) VALUES "
  . "( '$this->solc_fecha','$this->solc_destino','$this->solc_observacion','$this->solc_usuario',"
        . "'$this->solc_tipo' )";
 
 


$result = $this->database->query($sql);
$this->solc_id = mysql_insert_id();

}

// **********************
// UPDATE
// **********************
function updestado()
{
$solc_id= $this->getsolc_id();


$sql = " UPDATE ing_solicitud SET "
       
        . "solc_estado = '$this->solc_estado'  "
        . ""
        . "WHERE solc_id = $solc_id ";

$result = $this->database->query($sql);



}
function updsolicitud()
{
$solc_id= $this->getsolc_id();


$sql = " UPDATE ing_solicitud SET "
        . " solc_fecha = '$this->solc_fecha',solc_destino = '$this->solc_destino',"
        . "solc_observacion = '$this->solc_observacion' "
        . "  "
        . ""
        . "WHERE solc_id = $solc_id ";

$result = $this->database->query($sql);



}
function update($id)
{



$sql = " UPDATE ing_solicitud SET "
        . " solc_fecha = '$this->solc_fecha',solc_destino = '$this->solc_destino',"
        . "solc_observacion = '$this->solc_observacion',solc_usuario = '$this->solc_usuario',"
        . "solc_estado = '$this->solc_estado',solc_tipo = '$this->solc_tipo' "
        . ""
        . "WHERE solc_id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>