<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        cls_comuna
* GENERATION DATE:  27.03.2021
* CLASS FILE:       C:\xampp\htdocs\generator/generated_classes/class.cls_comuna.php
* FOR MYSQL TABLE:  comuna
* FOR MYSQL DB:     erp
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

require_once("../conexion/conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cls_comuna
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id_ciudad;   // KEY ATTR. WITH AUTOINCREMENT

var $id_region;   // (normal Attribute)
var $nombre_ciudad;   // (normal Attribute)
var $arrcomuna;

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function cls_comuna()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getid_ciudad()
{
return $this->id_ciudad;
}

function getid_region()
{
return $this->id_region;
}

function getnombre_ciudad()
{
return $this->nombre_ciudad;
}

// **********************
// SETTER METHODS
// **********************


function setid_ciudad($val)
{
$this->id_ciudad =  $val;
}

function setid_region($val)
{
$this->id_region =  $val;
}

function setnombre_ciudad($val)
{
$this->nombre_ciudad =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function selectdata()
{
$id = $this->getid_ciudad();
$sql =  "SELECT * FROM comuna WHERE 1;";
$result =  $this->database->query($sql);
$i=0;
    while($datos = $this->database->fetch_array($result)){
        
        $this->arrcomuna[$i]['id_ciudad'] = $datos['id_ciudad']; 
  
        $this->arrcomuna[$i]['id_region'] = $datos['id_region']; 
        $this->arrcomuna[$i]['nombre_ciudad'] = $datos['nombre_ciudad']; 
 
         
     $i++;
    } 
 

}

// **********************
// DELETE
// **********************

function delete()
{
    $id = $this->getid_ciudad();
$sql = "DELETE FROM comuna WHERE id_ciudad = '$id';";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id_ciudad = ""; // clear key for autoincrement

$sql = "INSERT INTO comuna ( id_region,nombre_ciudad ) VALUES ( '$this->id_region','$this->nombre_ciudad' )";
$result = $this->database->query($sql);
$this->id_ciudad = mysql_insert_id();

}

// **********************
// UPDATE
// **********************

function update()
{
$id = $this->getid_ciudad();


$sql = " UPDATE comuna SET  id_region = '$this->id_region',nombre_ciudad = '$this->nombre_ciudad' WHERE id_ciudad = '$id' ";

$result = $this->database->query($sql);



}


}?>