<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        cls_web_canasta
* GENERATION DATE:  25.05.2020
* CLASS FILE:       C:\xampp\htdocs\generator/generated_classes/class.cls_web_canasta.php
* FOR MYSQL TABLE:  web_canasta
* FOR MYSQL DB:     erp
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

require_once("../conexion/conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cls_web_canasta
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $canasta_id;   // KEY ATTR. WITH AUTOINCREMENT

var $canasta_codigo_prod;   // (normal Attribute)
var $canasta_cantidad_prod;   // (normal Attribute)
var $canasta_fecha;   // (normal Attribute)
var $canasta_hora;   // (normal Attribute)
var $canasta_estado;   // (normal Attribute)
var $canasta_rut;   // (normal Attribute)
var $canasta_precio;   // (normal Attribute)
var $arrcanasta;

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function cls_web_canasta()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getcanasta_id()
{
return $this->canasta_id;
}

function getcanasta_codigo_prod()
{
return $this->canasta_codigo_prod;
}

function getcanasta_cantidad_prod()
{
return $this->canasta_cantidad_prod;
}

function getcanasta_fecha()
{
return $this->canasta_fecha;
}

function getcanasta_hora()
{
return $this->canasta_hora;
}

function getcanasta_estado()
{
return $this->canasta_estado;
}

function getcanasta_rut()
{
return $this->canasta_rut;
}

function getcanasta_precio()
{
return $this->canasta_precio;
}

// **********************
// SETTER METHODS
// **********************


function setcanasta_id($val)
{
$this->canasta_id =  $val;
}

function setcanasta_codigo_prod($val)
{
$this->canasta_codigo_prod =  $val;
}

function setcanasta_cantidad_prod($val)
{
$this->canasta_cantidad_prod =  $val;
}

function setcanasta_fecha($val)
{
$this->canasta_fecha =  $val;
}

function setcanasta_hora($val)
{
$this->canasta_hora =  $val;
}

function setcanasta_estado($val)
{
$this->canasta_estado =  $val;
}

function setcanasta_rut($val)
{
$this->canasta_rut =  $val;
}

function setcanasta_precio($val)
{
$this->canasta_precio =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************
function selecdata(){
    $rut = $this->getcanasta_rut();
    $sql =  "SELECT * FROM web_canasta w inner join  proc_producto p "
            . " on p.prod_codigo= w.canasta_codigo_prod"
            . " WHERE w.canasta_rut = '$rut' ;";
$result =  $this->database->query($sql);
    $i=0;
    while($datos = $this->database->fetch_array($result)){
        
         $this->arrcanasta[$i]['prod_nombre'] = $datos['prod_nombre']; 
        $this->arrcanasta[$i]['canasta_id'] = $datos['canasta_id']; 
        $this->arrcanasta[$i]['canasta_codigo_prod'] = $datos['canasta_codigo_prod']; 
        $this->arrcanasta[$i]['canasta_cantidad_prod'] = $datos['canasta_cantidad_prod']; 
        $this->arrcanasta[$i]['canasta_fecha'] = $datos['canasta_fecha']; 
        $this->arrcanasta[$i]['canasta_hora'] = $datos['canasta_hora']; 
        $this->arrcanasta[$i]['canasta_estado'] = $datos['canasta_estado'];  
        $this->arrcanasta[$i]['canasta_rut'] = $datos['canasta_rut'];
        $this->arrcanasta[$i]['canasta_precio'] = $datos['canasta_precio'];
        


        $i++;
        
    }
}
// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM web_canasta WHERE canasta_id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->canasta_id = ""; // clear key for autoincrement

$sql = "INSERT INTO web_canasta "
  . "( canasta_codigo_prod,canasta_cantidad_prod,canasta_fecha,canasta_hora,canasta_estado,canasta_rut,canasta_precio ) VALUES"
  . " ( '$this->canasta_codigo_prod','$this->canasta_cantidad_prod','$this->canasta_fecha','$this->canasta_hora',"
  . "'$this->canasta_estado','$this->canasta_rut','$this->canasta_precio' )";
$result = $this->database->query($sql);
$this->canasta_id = mysql_insert_id();

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE web_canasta SET  canasta_codigo_prod = '$this->canasta_codigo_prod',canasta_cantidad_prod = '$this->canasta_cantidad_prod',canasta_fecha = '$this->canasta_fecha',canasta_hora = '$this->canasta_hora',canasta_estado = '$this->canasta_estado',canasta_rut = '$this->canasta_rut',canasta_precio = '$this->canasta_precio' WHERE canasta_id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>