
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        cls_det_solicitud
* GENERATION DATE:  11.04.2021
* CLASS FILE:       C:\xampp\htdocs\generator/generated_classes/class.cls_det_solicitud.php
* FOR MYSQL TABLE:  ing_solicitud
* FOR MYSQL DB:     erp
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("resources/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class cls_det_solicitud
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $dsolc_id;   // KEY ATTR. WITH AUTOINCREMENT

var $solc_id;   // (normal Attribute)
var $solc_fecha;   // (normal Attribute)
var $solc_destino;   // (normal Attribute)
var $solc_observacion;   // (normal Attribute)
var $solc_usuario;   // (normal Attribute)
var $solc_estado;   // (normal Attribute)
var $solc_tipo;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function cls_det_solicitud()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getsolc_id()
{
return $this->solc_id;
}

function getsolc_fecha()
{
return $this->solc_fecha;
}

function getsolc_destino()
{
return $this->solc_destino;
}

function getsolc_observacion()
{
return $this->solc_observacion;
}

function getsolc_usuario()
{
return $this->solc_usuario;
}

function getsolc_estado()
{
return $this->solc_estado;
}

function getsolc_tipo()
{
return $this->solc_tipo;
}

// **********************
// SETTER METHODS
// **********************


function setsolc_id($val)
{
$this->solc_id =  $val;
}

function setsolc_fecha($val)
{
$this->solc_fecha =  $val;
}

function setsolc_destino($val)
{
$this->solc_destino =  $val;
}

function setsolc_observacion($val)
{
$this->solc_observacion =  $val;
}

function setsolc_usuario($val)
{
$this->solc_usuario =  $val;
}

function setsolc_estado($val)
{
$this->solc_estado =  $val;
}

function setsolc_tipo($val)
{
$this->solc_tipo =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM ing_solicitud WHERE dsolc_id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->solc_id = $row->solc_id;

$this->solc_fecha = $row->solc_fecha;

$this->solc_destino = $row->solc_destino;

$this->solc_observacion = $row->solc_observacion;

$this->solc_usuario = $row->solc_usuario;

$this->solc_estado = $row->solc_estado;

$this->solc_tipo = $row->solc_tipo;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM ing_solicitud WHERE dsolc_id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->dsolc_id = ""; // clear key for autoincrement

$sql = "INSERT INTO ing_solicitud ( solc_id,solc_fecha,solc_destino,solc_observacion,solc_usuario,solc_estado,solc_tipo ) VALUES ( '$this->solc_id','$this->solc_fecha','$this->solc_destino','$this->solc_observacion','$this->solc_usuario','$this->solc_estado','$this->solc_tipo' )";
$result = $this->database->query($sql);
$this->dsolc_id = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE ing_solicitud SET  solc_id = '$this->solc_id',solc_fecha = '$this->solc_fecha',solc_destino = '$this->solc_destino',solc_observacion = '$this->solc_observacion',solc_usuario = '$this->solc_usuario',solc_estado = '$this->solc_estado',solc_tipo = '$this->solc_tipo' WHERE dsolc_id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
<!-- end of generated class -->
