<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        cls_proc_marca1
* GENERATION DATE:  06.09.2020
* CLASS FILE:       C:\xampp\htdocs\generator/generated_classes/class.cls_proc_marca1.php
* FOR MYSQL TABLE:  proc_marca1
* FOR MYSQL DB:     erp
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("resources/class.database.php");  //cambiar

// **********************
// CLASS DECLARATION
// **********************

class cls_proc_marca1
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $marca_id;   // KEY ATTR. WITH AUTOINCREMENT

var $marca_nombre;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function cls_proc_marca1()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getmarca_id()
{
return $this->marca_id;
}

function getmarca_nombre()
{
return $this->marca_nombre;
}

// **********************
// SETTER METHODS
// **********************


function setmarca_id($val)
{
$this->marca_id =  $val;
}

function setmarca_nombre($val)
{
$this->marca_nombre =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM proc_marca1 WHERE marca_id = $id;";
$result =  $this->database->query($sql);

$row = mysql_fetch_object($result);


$this->marca_id = $row->marca_id;

$this->marca_nombre = $row->marca_nombre;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM proc_marca1 WHERE marca_id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->marca_id = ""; // clear key for autoincrement

$sql = "INSERT INTO proc_marca1 ( marca_nombre ) VALUES ( '$this->marca_nombre' )";
$result = $this->database->query($sql);
$this->marca_id = mysql_insert_id();

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE proc_marca1 SET  marca_nombre = '$this->marca_nombre' WHERE marca_id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>