<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        cls_proc_categoria_producto
* GENERATION DATE:  14.01.2020
* CLASS FILE:       C:\xampp\htdocs\generator/generated_classes/class.cls_proc_categoria_producto.php
* FOR MYSQL TABLE:  proc_categoria_producto
* FOR MYSQL DB:     erp
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

require_once("../conexion/conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cls_proc_categoria_producto
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $cat_id;   // KEY ATTR. WITH AUTOINCREMENT

var $pro_cat_id;   // (normal Attribute)
var $cat_nombre;   // (normal Attribute)
var $cat_color;
var $cat_tipo;
var $cat_etiqueta;

var $arrcat;
var $arrsbcat;
var $arrsbsbcat;
var $total_categoria;
var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function cls_proc_categoria_producto()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getcat_id()
{
return $this->cat_id;
}

function getpro_cat_id()
{
return $this->pro_cat_id;
}

function getcat_nombre()
{
return $this->cat_nombre;
}
function getcat_color()
{
return $this->cat_color;
}
function getcat_tipo()
{
return $this->cat_tipo;
}
function getcat_etiqueta()
{
return $this->cat_etiqueta;
}
function gettotal_categoria()
{
return $this->total_categoria;
}
// **********************
// SETTER METHODS
// **********************


function setcat_id($val)
{
$this->cat_id =  $val;
}

function setpro_cat_id($val)
{
$this->pro_cat_id =  $val;
}

function setcat_nombre($val)
{
$this->cat_nombre =  $val;
}
function setcat_color($val)
{
$this->cat_color =  $val;
}
function setcat_tipo($val)
{
$this->cat_tipo =  $val;
}
function setcat_etiqueta($val)
{
$this->cat_etiqueta =  $val;
}
function settotal_categoria($val)
{
$this->total_categoria =  $val;
}
// **********************
// SELECT METHOD / LOAD
// **********************
function selectarbol()
{
$cat_id = $this->getcat_id();
//$pro_cat_id = 3;

$sql =  "select t.cat_id as id, @pv:=t.pro_cat_id as parent , t.cat_nombre, t.cat_etiqueta "
        . "from (select * from  proc_categoria_producto order by cat_id desc) t join "
        . "(select @pv:='$cat_id')tmp where t.cat_id=@pv; ";
$result =  $this->database->query($sql);
$i=0;
    while($datos = $this->database->fetch_array($result)){
        
        $this->arrcat[$i]['cat_id'] = $datos['id']; 
        $this->arrcat[$i]['pro_cat_id'] = $datos['parent']; 
        $this->arrcat[$i]['cat_nombre'] = $datos['cat_nombre']; 
        $this->arrcat[$i]['cat_etiqueta'] = $datos['cat_etiqueta']; 
    //    $this->arrcat[$i]['cat_color'] = $datos['cat_color']; 
     //   $this->arrcat[$i]['cat_etiqueta'] = $datos['cat_etiqueta']; 
         
     $i++;
    } 
}
function totalxcat()
{
$pro_cat_id = $this->getpro_cat_id();
$cat_tipo = $this->getcat_tipo();
if(!is_null($pro_cat_id) && intval($pro_cat_id) > 0 )
    $sql =  "SELECT count(*) as total_categoria FROM proc_categoria_producto WHERE  pro_cat_id = '$pro_cat_id' and cat_tipo = '$cat_tipo'";
else 
     $sql =  "SELECT count(*) as total_categoria FROM proc_categoria_producto WHERE  pro_cat_id is null  and cat_tipo = '$cat_tipo'";
   
$result = $this->database->query($sql);
 $i=0;
    while($datos = $this->database->fetch_array($result)){
       
        $this->total_categoria = $datos['total_categoria'];  
         $i++;
    } 
}
function selectsubcat()  //lista todo los nodos y hojas
{
$pro_cat_id = $this->getpro_cat_id();
//$pro_cat_id = 3;
$sql =  "select t.cat_id, t.pro_cat_id , t.cat_nombre, t.cat_etiqueta from (select * from  proc_categoria_producto"
        . " order by cat_nombre asc) t join (select @pv:='$pro_cat_id')tmp where  "
        . " find_in_set(pro_cat_id, @pv) and     length(@pv := concat(@pv, ',', cat_id ))";
$result =  $this->database->query($sql);
$i=0;
    while($datos = $this->database->fetch_array($result)){
        
        $this->arrcat[$i]['cat_id'] = $datos['cat_id']; 
        $this->arrcat[$i]['pro_cat_id'] = $datos['pro_cat_id']; 
        $this->arrcat[$i]['cat_nombre'] = $datos['cat_nombre']; 
        $this->arrcat[$i]['cat_color'] = $datos['cat_color']; 
        $this->arrcat[$i]['cat_etiqueta'] = $datos['cat_etiqueta']; 
         
     $i++;
    } 
}
function selectnodos()   
{
$pro_cat_id = $this->getpro_cat_id();
//$pro_cat_id = 3;
$sql =  "select cat_id, pro_cat_id ,cat_nombre, cat_etiqueta , cat_color from "
        . "  proc_categoria_producto where pro_cat_id = '$pro_cat_id' "
        . " order by cat_nombre asc ";
$result =  $this->database->query($sql);
$i=0;
    while($datos = $this->database->fetch_array($result)){
        
        $this->arrcat[$i]['cat_id'] = $datos['cat_id']; 
        $this->arrcat[$i]['pro_cat_id'] = $datos['pro_cat_id']; 
        $this->arrcat[$i]['cat_nombre'] = $datos['cat_nombre']; 
        $this->arrcat[$i]['cat_color'] = $datos['cat_color']; 
        $this->arrcat[$i]['cat_etiqueta'] = $datos['cat_etiqueta']; 
         
     $i++;
    } 
}
function getcatxnombre()
{
$pro_cat_id = $this->getpro_cat_id();
$cat_nombre = $this->getcat_nombre();
$cat_tipo = $this->getcat_tipo();
if(!is_null($pro_cat_id))
$sql =  "SELECT * FROM `proc_categoria_producto` WHERE `pro_cat_id` = '$pro_cat_id' and cat_tipo = '$cat_tipo' and cat_nombre LIKE '$cat_nombre' "
        . " order by cat_nombre asc  ;";
$result =  $this->database->query($sql);
$i=0;
    while($datos = $this->database->fetch_array($result)){
        
        $this->arrcat[$i]['cat_id'] = $datos['cat_id']; 
        $this->arrcat[$i]['pro_cat_id'] = $datos['pro_cat_id']; 
        $this->arrcat[$i]['cat_nombre'] = $datos['cat_nombre']; 
        $this->arrcat[$i]['cat_color'] = $datos['cat_color']; 
        $this->arrcat[$i]['cat_etiqueta'] = $datos['cat_etiqueta']; 
     $i++;
    } 
}
function getcatgeneralxnombre()
{
$cat_nombre = $this->getcat_nombre();
$cat_tipo = $this->getcat_tipo();
$sql =  "SELECT * FROM `proc_categoria_producto` WHERE `pro_cat_id` is null and cat_tipo = '$cat_tipo' and cat_nombre LIKE '$cat_nombre' "
        . " order by cat_nombre asc  ;";
$result =  $this->database->query($sql);
$i=0;
    while($datos = $this->database->fetch_array($result)){
        
        $this->arrcat[$i]['cat_id'] = $datos['cat_id']; 
        $this->arrcat[$i]['pro_cat_id'] = $datos['pro_cat_id']; 
        $this->arrcat[$i]['cat_nombre'] = $datos['cat_nombre']; 
        $this->arrcat[$i]['cat_color'] = $datos['cat_color']; 
        $this->arrcat[$i]['cat_etiqueta'] = $datos['cat_etiqueta']; 
     $i++;
    } 
}
function selectgeneral()
{
$cat_tipo = $this->getcat_tipo();
$sql =  "SELECT * FROM proc_categoria_producto WHERE pro_cat_id is null and cat_tipo = '$cat_tipo' order by cat_nombre asc ;";
$result =  $this->database->query($sql);
$i=0;
    while($datos = $this->database->fetch_array($result)){
        
        $this->arrcat[$i]['cat_id'] = $datos['cat_id']; 
        $this->arrcat[$i]['pro_cat_id'] = $datos['pro_cat_id']; 
        $this->arrcat[$i]['cat_nombre'] = $datos['cat_nombre']; 
        $this->arrcat[$i]['cat_color'] = $datos['cat_color']; 
        $this->arrcat[$i]['cat_etiqueta'] = $datos['cat_etiqueta']; 
     $i++;
    } 
}

function select($id)
{

$sql =  "SELECT * FROM proc_categoria_producto WHERE cat_id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->cat_id = $row->cat_id;

$this->pro_cat_id = $row->pro_cat_id;

$this->cat_nombre = $row->cat_nombre;

}

// **********************
// DELETE
// **********************

function delete()
{
 $id = $this->getcat_id();
$sql = "DELETE FROM proc_categoria_producto WHERE cat_id = '$id';";
$result = $this->database->query($sql);

}
 
// **********************
// INSERT
// **********************

function insert()
{
$this->cat_id = ""; // clear key for autoincrement
 
if(isset($this->pro_cat_id))
  $sql = "INSERT INTO proc_categoria_producto ( pro_cat_id,cat_nombre,cat_color, cat_tipo,cat_etiqueta )"
        . " VALUES ( '$this->pro_cat_id','$this->cat_nombre','$this->cat_color','$this->cat_tipo', '$this->cat_etiqueta' )";
else 
     $sql = "INSERT INTO proc_categoria_producto (  cat_nombre,cat_color, cat_tipo,cat_etiqueta )"
        . " VALUES (  '$this->cat_nombre','$this->cat_color','$this->cat_tipo', '$this->cat_etiqueta' )";
$result = $this->database->query($sql);
$this->cat_id = mysql_insert_id();

}

// **********************
// UPDATE
// **********************
function editar()
{

$id = $this->getcat_id();

$sql = " UPDATE proc_categoria_producto SET  cat_nombre = '$this->cat_nombre' WHERE cat_id = $id ";

$result = $this->database->query($sql);



}
function update()
{



$sql = " UPDATE proc_categoria_producto SET  pro_cat_id = '$this->pro_cat_id',cat_nombre = '$this->cat_nombre' WHERE cat_id = $id ";

$result = $this->database->query($sql);



}


} 

?>