<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        cls_telas_colores
* GENERATION DATE:  14.01.2020
* CLASS FILE:       C:\xampp\htdocs\generator/generated_classes/class.cls_telas_colores.php
* FOR MYSQL TABLE:  telas_colores
* FOR MYSQL DB:     erp
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

require_once("../conexion/conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cls_telas_colores
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $color_id;   // KEY ATTR. WITH AUTOINCREMENT

var $pro_color_id;   // (normal Attribute)
var $color_nombre;   // (normal Attribute)
var $color_color;
var $color_tipo;
var $color_etiqueta;

var $arrcolor;
var $arrsbmarca;
var $arrsbsbmarca;
var $total_marcaegoria;
var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function cls_telas_colores()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getcolor_id()
{
return $this->color_id;
}

function getpro_color_id()
{
return $this->pro_color_id;
}

function getcolor_nombre()
{
return $this->color_nombre;
}
function getcolor_color()
{
return $this->color_color;
}
function getcolor_tipo()
{
return $this->color_tipo;
}
function getcolor_etiqueta()
{
return $this->color_etiqueta;
}
function gettotal_marcaegoria()
{
return $this->total_marcaegoria;
}
// **********************
// SETTER METHODS
// **********************


function setcolor_id($val)
{
$this->color_id =  $val;
}

function setpro_color_id($val)
{
$this->pro_color_id =  $val;
}

function setcolor_nombre($val)
{
$this->color_nombre =  $val;
}
function setcolor_color($val)
{
$this->color_color =  $val;
}
function setcolor_tipo($val)
{
$this->color_tipo =  $val;
}
function setcolor_etiqueta($val)
{
$this->color_etiqueta =  $val;
}
function settotal_marcaegoria($val)
{
$this->total_marcaegoria =  $val;
}
// **********************
// SELECT METHOD / LOAD
// **********************
function selectarbol()
{
$color_id = $this->getcolor_id();
//$pro_color_id = 3;

$sql =  "select t.color_id as id, @pv:=t.pro_color_id as parent , t.color_nombre, t.color_etiqueta "
        . "from (select * from  telas_colores order by color_id desc) t join "
        . "(select @pv:='$color_id')tmp where t.color_id=@pv; ";
$result =  $this->database->query($sql);
$i=0;
    while($datos = $this->database->fetch_array($result)){
        
        $this->arrcolor[$i]['color_id'] = $datos['id']; 
     //   $this->arrcolor[$i]['pro_color_id'] = $datos['parent']; 
        $this->arrcolor[$i]['color_nombre'] = $datos['color_nombre']; 
        $this->arrcolor[$i]['color_etiqueta'] = $datos['color_etiqueta']; 
    //    $this->arrcolor[$i]['color_color'] = $datos['color_color']; 
     //   $this->arrcolor[$i]['color_etiqueta'] = $datos['color_etiqueta']; 
         
     $i++;
    } 
}
function totalxmarca()
{
$pro_color_id = $this->getpro_color_id();
$color_tipo = $this->getcolor_tipo();
if(!is_null($pro_color_id))
    $sql =  "SELECT count(*) as total_marcaegoria FROM telas_colores WHERE  pro_color_id = '$pro_color_id' and color_tipo = '$color_tipo'";
else 
     $sql =  "SELECT count(*) as total_marcaegoria FROM telas_colores WHERE  pro_color_id is null  and color_tipo = '$color_tipo'";
   
$result = $this->database->query($sql);
 $i=0;
    while($datos = $this->database->fetch_array($result)){
       
        $this->total_marcaegoria = $datos['total_marcaegoria'];  
         $i++;
    } 
}
function selectsubmarca()
{
$pro_color_id = $this->getpro_color_id();
//$pro_color_id = 3;
$sql =  "select t.color_id, t.pro_color_id , t.color_nombre, t.color_etiqueta from (select * from  telas_colores"
        . " order by color_nombre asc) t join (select @pv:='$pro_color_id')tmp where  "
        . " find_in_set(pro_color_id, @pv) and     length(@pv := conmarca(@pv, ',', color_id ))";
$result =  $this->database->query($sql);
$i=0;
    while($datos = $this->database->fetch_array($result)){
        
        $this->arrcolor[$i]['color_id'] = $datos['color_id']; 
   //     $this->arrcolor[$i]['pro_color_id'] = $datos['pro_color_id']; 
        $this->arrcolor[$i]['color_nombre'] = $datos['color_nombre']; 
        $this->arrcolor[$i]['color_color'] = $datos['color_color']; 
        $this->arrcolor[$i]['color_etiqueta'] = $datos['color_etiqueta']; 
         
     $i++;
    } 
}
function buscadatanombre()
{
$color_nombre = $this->getcolor_nombre();
$color_tipo = $this->getcolor_tipo();
$sql =  "SELECT * FROM `telas_colores` WHERE  color_nombre = '$color_nombre' "
        . " order by color_nombre asc  ;";
$result =  $this->database->query($sql);
$i=0;
    while($datos = $this->database->fetch_array($result)){
        
        $this->arrcolor[$i]['color_id'] = $datos['color_id']; 
 //       $this->arrcolor[$i]['pro_color_id'] = $datos['pro_color_id']; 
        $this->arrcolor[$i]['color_nombre'] = $datos['color_nombre']; 
        $this->arrcolor[$i]['color_color'] = $datos['color_color']; 
        $this->arrcolor[$i]['color_etiqueta'] = $datos['color_etiqueta']; 
     $i++;
    } 
}
function selectdata()
{
$color_tipo = $this->getcolor_tipo();
$sql =  "SELECT * FROM telas_colores WHERE 1 order by color_nombre asc   ;";
$result =  $this->database->query($sql);
$i=0;
    while($datos = $this->database->fetch_array($result)){
        
        $this->arrcolor[$i]['color_id'] = $datos['color_id']; 
//        $this->arrcolor[$i]['pro_color_id'] = $datos['pro_color_id']; 
        $this->arrcolor[$i]['color_nombre'] = $datos['color_nombre']; 
        $this->arrcolor[$i]['color_html'] = $datos['color_html']; 
    //    $this->arrcolor[$i]['color_etiqueta'] = $datos['color_etiqueta']; 
     $i++;
    } 
}

function select($id)
{

$sql =  "SELECT * FROM telas_colores WHERE color_id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->color_id = $row->color_id;

$this->pro_color_id = $row->pro_color_id;

$this->color_nombre = $row->color_nombre;

}

// **********************
// DELETE
// **********************

function delete()
{
 $id = $this->getcolor_id();
$sql = "DELETE FROM telas_colores WHERE color_id = '$id';";
$result = $this->database->query($sql);

}
 
// **********************
// INSERT
// **********************

function insert()
{
$this->color_id = ""; // clear key for autoincrement

     $sql = "INSERT INTO telas_colores (  color_nombre)"
        . " VALUES (  '$this->color_nombre' )";
$result = $this->database->query($sql);
$this->color_id = mysql_insert_id();

}

// **********************
// UPDATE
// **********************
function editar()
{

$id = $this->getcolor_id();

$sql = " UPDATE telas_colores SET  color_nombre = '$this->color_nombre' WHERE color_id = $id ";

$result = $this->database->query($sql);



}
function update()
{



$sql = " UPDATE telas_colores SET  pro_color_id = '$this->pro_color_id',color_nombre = '$this->color_nombre' WHERE color_id = $id ";

$result = $this->database->query($sql);



}


} 

?>