
<!-- begin of generated class -->
<?php
/*
 *
 * -------------------------------------------------------
 * CLASSNAME:        cls_vta_doc_salida
 * GENERATION DATE:  28.06.2021
 * CLASS FILE:       C:\xampp\htdocs\generator/generated_classes/class.cls_vta_doc_salida.php
 * FOR MYSQL TABLE:  vta_doc_salida
 * FOR MYSQL DB:     pyventas
 * -------------------------------------------------------
 * CODE GENERATED BY:
 * MY PHP-MYSQL-CLASS GENERATOR
 * from: >> www.voegeli.li >> (download for free!)
 * -------------------------------------------------------
 *
 */

include_once('../conexion/conexion.php');

// **********************
// CLASS DECLARATION
// **********************

class cls_vta_doc_salida { // class : begin
// **********************
// ATTRIBUTE DECLARATION
// **********************

    var $SAL_IDENT;   // KEY ATTR. WITH AUTOINCREMENT
    var $SAL_TIPODOC2;   // (normal Attribute)
    var $PTOVTA_ID;   // (normal Attribute)
    var $CLIENTE_RUT;   // (normal Attribute)
    var $VTA_SAL_IDENT;   // (normal Attribute)
    var $VTA_SAL_TIPODOC2;   // (normal Attribute)
    var $SAL_NUMERODOC;   // (normal Attribute)
    var $SAL_FECHAPEDIDO;   // (normal Attribute)
    var $SAL_FECHADOC;   // (normal Attribute)
    var $SAL_DATE;   // (normal Attribute)
    var $SAL_IVA;   // (normal Attribute)
    var $SAL_NETO;   // (normal Attribute)
    var $SAL_TOTAL;   // (normal Attribute)
    var $SAL_VENDEDOR;   // (normal Attribute)
    var $SAL_ACTUALIZA;   // (normal Attribute)
    var $SAL_FORMADEPAGO;   // (normal Attribute)
    var $SAL_NUMEROPEDIDO;   // (normal Attribute)
    var $SAL_ESTADO;   // (normal Attribute)
    var $SAL_OBS;   // (normal Attribute)
    var $SAL_TIPO_DESCUENTO;   // (normal Attribute)
    var $SAL_DESCUENTO;   // (normal Attribute)
    var $SAL_EXENTA;   // (normal Attribute)
    var $SAL_ENVIA_SII;   // (normal Attribute)
    var $SAL_ESTADO_PAGO;   // (normal Attribute)
    var $database; // Instance of class database

// **********************
// CONSTRUCTOR METHOD
// **********************

    function cls_vta_doc_salida() {

        $this->database = new Database();
    }

// **********************
// GETTER METHODS
// **********************


    function getSAL_IDENT() {
        return $this->SAL_IDENT;
    }

    function getSAL_TIPODOC2() {
        return $this->SAL_TIPODOC2;
    }

    function getPTOVTA_ID() {
        return $this->PTOVTA_ID;
    }

    function getCLIENTE_RUT() {
        return $this->CLIENTE_RUT;
    }

    function getVTA_SAL_IDENT() {
        return $this->VTA_SAL_IDENT;
    }

    function getVTA_SAL_TIPODOC2() {
        return $this->VTA_SAL_TIPODOC2;
    }

    function getSAL_NUMERODOC() {
        return $this->SAL_NUMERODOC;
    }

    function getSAL_FECHAPEDIDO() {
        return $this->SAL_FECHAPEDIDO;
    }

    function getSAL_FECHADOC() {
        return $this->SAL_FECHADOC;
    }

    function getSAL_DATE() {
        return $this->SAL_DATE;
    }

    function getSAL_IVA() {
        return $this->SAL_IVA;
    }

    function getSAL_NETO() {
        return $this->SAL_NETO;
    }

    function getSAL_TOTAL() {
        return $this->SAL_TOTAL;
    }

    function getSAL_VENDEDOR() {
        return $this->SAL_VENDEDOR;
    }

    function getSAL_ACTUALIZA() {
        return $this->SAL_ACTUALIZA;
    }

    function getSAL_FORMADEPAGO() {
        return $this->SAL_FORMADEPAGO;
    }

    function getSAL_NUMEROPEDIDO() {
        return $this->SAL_NUMEROPEDIDO;
    }

    function getSAL_ESTADO() {
        return $this->SAL_ESTADO;
    }

    function getSAL_OBS() {
        return $this->SAL_OBS;
    }

    function getSAL_TIPO_DESCUENTO() {
        return $this->SAL_TIPO_DESCUENTO;
    }

    function getSAL_DESCUENTO() {
        return $this->SAL_DESCUENTO;
    }

    function getSAL_EXENTA() {
        return $this->SAL_EXENTA;
    }

    function getSAL_ENVIA_SII() {
        return $this->SAL_ENVIA_SII;
    }

    function getSAL_ESTADO_PAGO() {
        return $this->SAL_ESTADO_PAGO;
    }

// **********************
// SETTER METHODS
// **********************


    function setSAL_IDENT($val) {
        $this->SAL_IDENT = $val;
    }

    function setSAL_TIPODOC2($val) {
        $this->SAL_TIPODOC2 = $val;
    }

    function setPTOVTA_ID($val) {
        $this->PTOVTA_ID = $val;
    }

    function setCLIENTE_RUT($val) {
        $this->CLIENTE_RUT = $val;
    }

    function setVTA_SAL_IDENT($val) {
        $this->VTA_SAL_IDENT = $val;
    }

    function setVTA_SAL_TIPODOC2($val) {
        $this->VTA_SAL_TIPODOC2 = $val;
    }

    function setSAL_NUMERODOC($val) {
        $this->SAL_NUMERODOC = $val;
    }

    function setSAL_FECHAPEDIDO($val) {
        $this->SAL_FECHAPEDIDO = $val;
    }

    function setSAL_FECHADOC($val) {
        $this->SAL_FECHADOC = $val;
    }

    function setSAL_DATE($val) {
        $this->SAL_DATE = $val;
    }

    function setSAL_IVA($val) {
        $this->SAL_IVA = $val;
    }

    function setSAL_NETO($val) {
        $this->SAL_NETO = $val;
    }

    function setSAL_TOTAL($val) {
        $this->SAL_TOTAL = $val;
    }

    function setSAL_VENDEDOR($val) {
        $this->SAL_VENDEDOR = $val;
    }

    function setSAL_ACTUALIZA($val) {
        $this->SAL_ACTUALIZA = $val;
    }

    function setSAL_FORMADEPAGO($val) {
        $this->SAL_FORMADEPAGO = $val;
    }

    function setSAL_NUMEROPEDIDO($val) {
        $this->SAL_NUMEROPEDIDO = $val;
    }

    function setSAL_ESTADO($val) {
        $this->SAL_ESTADO = $val;
    }

    function setSAL_OBS($val) {
        $this->SAL_OBS = $val;
    }

    function setSAL_TIPO_DESCUENTO($val) {
        $this->SAL_TIPO_DESCUENTO = $val;
    }

    function setSAL_DESCUENTO($val) {
        $this->SAL_DESCUENTO = $val;
    }

    function setSAL_EXENTA($val) {
        $this->SAL_EXENTA = $val;
    }

    function setSAL_ENVIA_SII($val) {
        $this->SAL_ENVIA_SII = $val;
    }

    function setSAL_ESTADO_PAGO($val) {
        $this->SAL_ESTADO_PAGO = $val;
    }

// **********************
// SELECT METHOD / LOAD
// **********************

    function select() {
        $SAL_IDENT = $this->SAL_IDENT;

        $sql = "SELECT * FROM vta_doc_salida WHERE SAL_IDENT = $SAL_IDENT;";
        $result = $this->database->query($sql);

        $row = mysql_fetch_object($result);


        $this->SAL_IDENT = $row->SAL_IDENT;

        $this->SAL_TIPODOC2 = $row->SAL_TIPODOC2;

        $this->PTOVTA_ID = $row->PTOVTA_ID;

        $this->CLIENTE_RUT = $row->CLIENTE_RUT;

        $this->VTA_SAL_IDENT = $row->VTA_SAL_IDENT;

        $this->VTA_SAL_TIPODOC2 = $row->VTA_SAL_TIPODOC2;

        $this->SAL_NUMERODOC = $row->SAL_NUMERODOC;

        $this->SAL_FECHAPEDIDO = $row->SAL_FECHAPEDIDO;

        $this->SAL_FECHADOC = $row->SAL_FECHADOC;

        $this->SAL_DATE = $row->SAL_DATE;

        $this->SAL_IVA = $row->SAL_IVA;

        $this->SAL_NETO = $row->SAL_NETO;

        $this->SAL_TOTAL = $row->SAL_TOTAL;

        $this->SAL_VENDEDOR = $row->SAL_VENDEDOR;

        $this->SAL_ACTUALIZA = $row->SAL_ACTUALIZA;

        $this->SAL_FORMADEPAGO = $row->SAL_FORMADEPAGO;

        $this->SAL_NUMEROPEDIDO = $row->SAL_NUMEROPEDIDO;

        $this->SAL_ESTADO = $row->SAL_ESTADO;

        $this->SAL_OBS = $row->SAL_OBS;

        $this->SAL_TIPO_DESCUENTO = $row->SAL_TIPO_DESCUENTO;

        $this->SAL_DESCUENTO = $row->SAL_DESCUENTO;

        $this->SAL_EXENTA = $row->SAL_EXENTA;

        $this->SAL_ENVIA_SII = $row->SAL_ENVIA_SII;

        $this->SAL_ESTADO_PAGO = $row->SAL_ESTADO_PAGO;
    }

// **********************
// DELETE
// **********************

    function delete($id) {
        $SAL_IDENT = $this->SAL_IDENT;
        $sql = "DELETE FROM vta_doc_salida WHERE SAL_IDENT = $SAL_IDENT;";
        $result = $this->database->query($sql);
    }

// **********************
// INSERT
// **********************

    function insert() {
        //  $this->SAL_IDENT = ""; // clear key for autoincrement

        $sql = "INSERT INTO vta_doc_salida ( SAL_TIPODOC2,PTOVTA_ID,CLIENTE_RUT,VTA_SAL_IDENT,VTA_SAL_TIPODOC2,SAL_NUMERODOC,SAL_FECHAPEDIDO,SAL_FECHADOC,SAL_DATE,SAL_IVA,SAL_NETO,SAL_TOTAL,SAL_VENDEDOR,SAL_ACTUALIZA,SAL_FORMADEPAGO,SAL_NUMEROPEDIDO,SAL_ESTADO,SAL_OBS,SAL_TIPO_DESCUENTO,SAL_DESCUENTO,SAL_EXENTA,SAL_ENVIA_SII,SAL_ESTADO_PAGO ) VALUES ( '$this->SAL_TIPODOC2','$this->PTOVTA_ID','$this->CLIENTE_RUT','$this->VTA_SAL_IDENT','$this->VTA_SAL_TIPODOC2','$this->SAL_NUMERODOC','$this->SAL_FECHAPEDIDO','$this->SAL_FECHADOC','$this->SAL_DATE','$this->SAL_IVA','$this->SAL_NETO','$this->SAL_TOTAL','$this->SAL_VENDEDOR','$this->SAL_ACTUALIZA','$this->SAL_FORMADEPAGO','$this->SAL_NUMEROPEDIDO','$this->SAL_ESTADO','$this->SAL_OBS','$this->SAL_TIPO_DESCUENTO','$this->SAL_DESCUENTO','$this->SAL_EXENTA','$this->SAL_ENVIA_SII','$this->SAL_ESTADO_PAGO' )";
        $result = $this->database->query($sql);
        $this->SAL_IDENT = mysql_insert_id($this->database->link);
    }

// **********************
// UPDATE
// **********************

    function update() {

        $SAL_IDENT = $this->SAL_IDENT;

        $sql = " UPDATE vta_doc_salida SET  SAL_TIPODOC2 = '$this->SAL_TIPODOC2',PTOVTA_ID = '$this->PTOVTA_ID',CLIENTE_RUT = '$this->CLIENTE_RUT',VTA_SAL_IDENT = '$this->VTA_SAL_IDENT',VTA_SAL_TIPODOC2 = '$this->VTA_SAL_TIPODOC2',SAL_NUMERODOC = '$this->SAL_NUMERODOC',SAL_FECHAPEDIDO = '$this->SAL_FECHAPEDIDO',SAL_FECHADOC = '$this->SAL_FECHADOC',SAL_DATE = '$this->SAL_DATE',SAL_IVA = '$this->SAL_IVA',SAL_NETO = '$this->SAL_NETO',SAL_TOTAL = '$this->SAL_TOTAL',SAL_VENDEDOR = '$this->SAL_VENDEDOR',SAL_ACTUALIZA = '$this->SAL_ACTUALIZA',SAL_FORMADEPAGO = '$this->SAL_FORMADEPAGO',SAL_NUMEROPEDIDO = '$this->SAL_NUMEROPEDIDO',SAL_ESTADO = '$this->SAL_ESTADO',SAL_OBS = '$this->SAL_OBS',SAL_TIPO_DESCUENTO = '$this->SAL_TIPO_DESCUENTO',SAL_DESCUENTO = '$this->SAL_DESCUENTO',SAL_EXENTA = '$this->SAL_EXENTA',SAL_ENVIA_SII = '$this->SAL_ENVIA_SII',SAL_ESTADO_PAGO = '$this->SAL_ESTADO_PAGO' WHERE SAL_IDENT = $SAL_IDENT ";

        $result = $this->database->query($sql);
    }

}

// class : end
?>
<!-- end of generated class -->
