
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        clscomuna
* GENERATION DATE:  15.07.2017
* CLASS FILE:       /var/www/generator/generated_classes/class.clscomuna.php
* FOR MYSQL TABLE:  comuna
* FOR MYSQL DB:     pacientes
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

require_once("../conexion/conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class clscomuna
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id_ciudad;   // KEY ATTR. WITH AUTOINCREMENT

var $id_region;   // (normal Attribute)
var $nombre_ciudad;   // (normal Attribute)
var $arrcomuna;

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function clscomuna()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getid_ciudad()
{
return $this->id_ciudad;
}

function getid_region()
{
return $this->id_region;
}

function getnombre_ciudad()
{
return $this->nombre_ciudad;
}

// **********************
// SETTER METHODS
// **********************


function setid_ciudad($val)
{
$this->id_ciudad =  $val;
}

function setid_region($val)
{
$this->id_region =  $val;
}

function setnombre_ciudad($val)
{
$this->nombre_ciudad =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************
function msolistacomunasxregion()
{
$id = $this->id_region;
$sql =  "SELECT * FROM comuna WHERE id_region = '$id' order by nombre_ciudad asc;";
$result =  $this->database->query($sql);

$i=0;
    while($row = $this->database->fetch_array($result)){


     $this->arrcomuna[$i]['id_ciudad'] = $row['id_ciudad'];
     $this->arrcomuna[$i]['id_region'] = $row['id_region'];
     $this->arrcomuna[$i]['nombre_ciudad'] = $row['nombre_ciudad'];
   $i++;
    }
}
function select($id)
{

$sql =  "SELECT * FROM comuna WHERE id_ciudad = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->id_ciudad = $row->id_ciudad;

$this->id_region = $row->id_region;

$this->nombre_ciudad = $row->nombre_ciudad;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM comuna WHERE id_ciudad = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id_ciudad = ""; // clear key for autoincrement

$sql = "INSERT INTO comuna ( id_region,nombre_ciudad ) VALUES ( '$this->id_region','$this->nombre_ciudad' )";
$result = $this->database->query($sql);
$this->id_ciudad = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE comuna SET  id_region = '$this->id_region',nombre_ciudad = '$this->nombre_ciudad' WHERE id_ciudad = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
<!-- end of generated class -->